navigation:
- text: Strategy / UX
  relative_url: strategy
  url: /strategy.html
- text: Creative
  relative_url: creative
  url: /creative.html
- text: Front-end
  relative_url: frontend
  url: /frontend.html
- text: Back-end
  relative_url: backend
  url: /backend.html
- text: Servers
  relative_url: servers
  url: /servers.html
- text: Deployment
  relative_url: deployment
  url: /deployment.html
markdown: kramdown
